#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2026. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
---
apiVersion: deploy.ibm.com/v1
kind: Environment
metadata:
  name: "BankZ-Development"
  version: 1.0.0

# Exclude the map temporary (not in the Bank of Z default intallation)
excludes_artifacts:
- .*BNK1B2M.*

# variables that can be overridden via extra vars
application: "{{ application if application is defined else '' }}"
hlq: "{{ extra_vars.hlq if extra_vars.hlq is defined else 'BANKZ.V0R1M0' }}"
uss_root: "{{ extra_vars.uss_root if extra_vars.uss_root is defined else '/tmp/wazi-deploy/int' }}"
deploy_cfg_home: "{{  extra_vars.deploy_cfg_home if extra_vars.deploy_cfg_home is defined else '/var/wazi-deploy-config-sample' }}"

#################################################################################
# This contains the 
# Environment specific settings according to the parent folder name
#################################################################################

# CICS
default_cics_user: "IBMUSER"
default_cics_password: ""
default_cics_context: "CICSBOZ"
default_cmci_host: "127.0.0.1"
default_cmci_port: 27100
default_cmci_scheme: "http"
default_csd_group: "BANKZGRP"
default_cics_cmci_action: "NEWCOPY"
default_env_cics_sdfhload: "{{default_cics_context}}.CICS.SDFHLOAD"
default_env_cics_csd: "{{default_cics_context}}.DFHCSD"
default_cmci_insecure: True
default_cmci_cert: ""
default_cmci_key: ""

# IMS
default_ims_host: "127.0.0.1"
default_ims_port: 9977
default_ims_user: "deb"
default_ims_password: ""
default_ims_datastore: "IMS2"

# Db2
default_db2_sdsnload: "DB2V13.SDSNLOAD"
default_pkg_jobcard: "BINDPKG JOB 'WD-PKGBIND',MSGLEVEL=(1,1),MSGCLASS=R,NOTIFY=&SYSUID"
default_plan_jobcard: "BINDPLA JOB 'WD-PLANBIND',MSGLEVEL=(1,1),MSGCLASS=R,NOTIFY=&SYSUID"
default_db2_sqlid: "IBMUSER"
default_db2_package: "BANKZPACK"
default_db2_plan: "BANKZPLN"
default_db2_qualifier: "IBMUSER"
default_db2_subsys: "DBD1"
default_db2_plan_pklist: "NULLID.*,BANKZPACK.*"
default_db2_action: "REPLACE"

# z/OS Connect
zos_connect_root: "{{ extra_vars.zos_connect_root if extra_vars.zos_connect_root is defined else '/var/zosconnect/servers/wazideploy-cics' }}"
zos_connect_job_name: "{{ extra_vars.zos_connect_job_name if extra_vars.zos_connect_job_name is defined else 'BAQBANKZ' }}"
zosconnect_http_port: "{{ extra_vars.zosconnect_http_port if extra_vars.zosconnect_http_port is defined else '9080' }}"
cics_host: "{{ extra_vars.cics_host if extra_vars.cics_host is defined else 'localhost' }}"
cics_port: "{{ extra_vars.cics_port if extra_vars.cics_port is defined else '2006' }}"
cics_user: "{{ extra_vars.cics_user if extra_vars.cics_user is defined else 'IBMUSER' }}"
cics_password: "{{ extra_vars.cics_password if extra_vars.cics_password is defined else '' }}" #pragma: allowlist secret

# IMS
ims_host: "{{ extra_vars.ims_host if extra_vars.ims_host is defined else 'localhost' }}"
ims_port: "{{ extra_vars.ims_port if extra_vars.ims_port is defined else '9977' }}"
ims_user: "{{ extra_vars.ims_user if extra_vars.ims_user is defined else 'deb' }}"
ims_password: "{{ extra_vars.ims_password if extra_vars.ims_password is defined else '' }}" #pragma: allowlist secret
ims_datastore: "{{ extra_vars.ims_datastore if extra_vars.ims_datastore is defined else 'IMS2' }}"


template_name_zosconnect_config:
  src: '../deploy/zos_connect_app_config.xml.j2'
  dest: '{{zos_connect_root}}/configDropins/overrides/{{api_name}}.xml'
  mode: 0755
  delegate: False


# System commands for z/OS Connect server management
system_command_start_server:
  cmd: 'S {{zos_connect_job_name}}'
  verbose: false
  wait_time_s: 5
  wait: true

system_command_refresh_config:
  cmd: 'MODIFY {{zos_connect_job_name}},REFRESH,CONFIG'
  verbose: false
  wait_time_s: 3
  wait: true

system_command_refresh_apps:
  cmd: 'MODIFY {{zos_connect_job_name}},REFRESH,APPS'
  verbose: false
  wait_time_s: 3
  wait: true

# load shared configuration
include_global_config:
  files_list:
    - "{{ deploy_cfg_home }}/deployment-configuration/global/global_initialization.yml"
  files_must_exist: true

